spark:
  - app.name: sparkEtl
  - spark.master: local
  - spark.dynamicAllocation.enabled: "true"
  - spark.shuffle.service.enabled: "true"
  - spark.driver.userClassPathFirst: "true"
  - spark.sql.orc.filterPushdown: "true"

elastic:
  - cluster.name: "localhost"
  - es.nodes: "localhost:9200"
  - es.net.http.auth.user: "elastic"
  - es.net.http.auth.pass: "password"
  - es.port: "9200"
  - es.nodes.wan.only: "true"
  - client.transport.sniff: "true"
  - client.transport.ignore_cluster_name: "true"
  - es.batch.write.refresh: "false"
  - es.batch.size.entries: "5000"
  - es.batch.write.retry.count: "2"
  - es.batch.write.retry.wait: "10s"
  - index.number_of_replicas: "0"
  - index.auto.create: "false"
